#kong-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  type: NodePort
  selector:
    app: kong
  ports:
  - name: http-proxy
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31000
  - name: https-proxy
    protocol: TCP
    port: 8443
    targetPort: 8443
    nodePort: 31001
  - name: admin-api
    protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 31002
  - name: admin-api-https
    protocol: TCP
    port: 8444
    targetPort: 8444
    nodePort: 31003
