#konga-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: konga
spec:
  type: NodePort
  selector:
    app: konga
  ports:
  - protocol: TCP
    port: 1337  # Konga Port
    targetPort: 1337
    nodePort: 32000