apiVersion: v1
kind: Pod
metadata:
  name: temporary-kong-pod
spec:
  containers:
  - name: kong
    image: kong:latest
    env:
    - name: KONG_DATABASE
      value: "postgres"
    - name: KONG_PG_HOST
      value: "172.16.22.122"
    - name: KONG_PG_PORT
      value: "31005"
    - name: KONG_PG_USER
      value: "kong"
    - name: KONG_PG_PASSWORD
      value: "kong"
    - name: KONG_PG_DATABASE
      value: "kong"
    command: [ "sh", "-c", "kong migrations bootstrap && tail -f /dev/null" ]

